# Generated by Django 3.0.14 on 2023-06-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='author',
        ),
    ]
