# Generated by Django 3.0.14 on 2023-06-16 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0010_remove_ai_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(limit_choices_to={'is_pulic': True}, on_delete=django.db.models.deletion.CASCADE, to='instagram.Post'),
        ),
    ]
