# Generated by Django 3.0.14 on 2023-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20230621_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ai/post/%Y/%m/%d'),
        ),
    ]
