# Generated by Django 3.1 on 2023-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_aidetail_inferencemodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
