# Generated by Django 3.0.14 on 2023-07-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo', '0002_auto_20230704_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
    ]
