# Generated by Django 3.1 on 2023-07-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20230705_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='result_url',
        ),
        migrations.AddField(
            model_name='ai',
            name='result',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
