# Generated by Django 3.1 on 2023-07-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aidetail_inferencemodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencemodel',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai.task'),
            preserve_default=False,
        ),
    ]
