# Generated by Django 3.1 on 2023-07-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_inferencemodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidetail',
            name='model_name',
        ),
    ]
