# Generated by Django 3.1 on 2023-07-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_remove_aidetail_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidetail',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_aidetail_set', to='ai.task'),
        ),
    ]
