# Generated by Django 3.1 on 2023-08-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20230718_1345'),
        ('ai', '0007_auto_20230717_1134'),
    ]

    operations = [
    ]
